added validation for checkoutForm
Galkevich-Natalia/Taste_Vista pull request #20
Opened 2024-04-23 20:46 UTC by Galkevich-Natalia

2024-04-26 19:39 UTC, AnnMurr requested changes

2024-04-26 19:39 UTC, AnnMurr commented on src/components/validation/validation.js
> +        messageName.textContent = 'Проверьте данные Name';
your website in English
your error messagies in Russian

2024-04-26 19:39 UTC, AnnMurr commented on src/components/validation/validation.js
> +export function checkValidation() {
rename

2024-04-26 19:39 UTC, AnnMurr commented on src/components/validation/validation.js
>      const body = document.querySelector('body');
checkValidation and  closeCheckoutModal mustn't be in validation file

2024-05-01 11:46 UTC, AnnMurr approved these changes

2024-05-01 11:46 UTC, AnnMurr commented on src/components/checkout/checkout.js
> +
you can remove these all

2024-05-01 11:46 UTC, AnnMurr commented on src/components/checkout/checkout.js
> +    if (validateForm()) {
define validateForm() into a variable

2024-05-01 11:46 UTC, AnnMurr commented on src/components/validation/validation.js
>          return false;
you have the same code many times, so you can create  a separate function

2024-05-01 11:46 UTC, AnnMurr commented on src/components/validation/validation.js
>          return false;
the same in else block

2024-05-01 11:46 UTC, AnnMurr commented on src/components/validation/validation.js
>      const name = document.getElementById('name').value;
it's not just name it's name value

2024-05-01 11:46 UTC, AnnMurr commented on src/components/validation/validation.js
>      const phone = document.getElementById('phone').value;
the same

2024-05-01 11:49 UTC, AnnMurr requested changes

2024-05-01 11:49 UTC, AnnMurr commented on src/components/checkout/checkout.js
>  import { getOrdersDataToStorage } from "../../utils/localStorage";
kmk.

2024-05-01 11:52 UTC, AnnMurr requested changes

2024-05-01 11:52 UTC, AnnMurr commented on src/components/checkout/checkout.js
>  import { getOrdersDataToStorage } from "../../utils/localStorage";
kllkm

2024-05-01 11:58 UTC, Galkevich-Natalia commented on src/components/checkout/checkout.js
>  import { getOrdersDataToStorage } from "../../utils/localStorage";
?

2024-05-01 12:06 UTC, AnnMurr commented on src/components/checkout/checkout.js
>  import { getOrdersDataToStorage } from "../../utils/localStorage";
don't pay attention

2024-05-06 06:39 UTC, AnnMurr requested changes

2024-05-06 06:39 UTC, AnnMurr commented on src/components/validation/validation.js
> +
can you move "return false/true" in these functions?

2024-05-06 09:33 UTC, AnnMurr approved these changes

2024-05-06 11:57 UTC, merged